package com.famandexpertapp1.core.domain.model

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

@Parcelize
data class Games(
    val keywords: List<Int?>,
    val rating: Double,
    val similarGames: List<Int?>,
    val createdAt: Int,
    val videos: List<Int?>,
    val aggregatedRatingCount: Int,
    val alternativeNames: List<Int?>,
    val playerPerspectives: List<Int?>,
    val screenshots: List<Int?>,
    val platforms: List<Int?>,
    val cover: Int,
    val themes: List<Int?>,
    val ageRatings: List<Int?>,
    val updatedAt: Int,
    val collections: List<Int?>,
    val firstReleaseDate: Int,
    val genres: List<Int?>,
    val releaseDates: List<Int?>,
    val storyline: String,
    val checksum: String,
    val totalRating: Double,
    val id: Int,
    val parentGame: Int,
    val slug: String,
    val hypes: Int,
    val franchises: List<Int?>,
    val summary: String,
    val gameModes: List<Int?>,
    val externalGames: List<Int?>,
    val url: String,
    val ratingCount: Int,
    val tags: List<Int?>,
    val languageSupports: List<Int?>,
    val artworks: List<Int?>,
    val name: String,
    val totalRatingCount: Int,
    val aggregatedRating: Double,
    val gameEngines: List<Int?>,
    val websites: List<Int?>,
    val category: Int,
    val involvedCompanies: List<Int?>,
    val isFavorite: Boolean,
) : Parcelable