package com.famandexpertapp1.core.domain.model

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

@Parcelize
data class Games(
    var keywords: List<Int?>,
    var rating: Double,
    var similarGames: List<Int?>,
    var createdAt: Int,
    var videos: List<Int?>,
    var aggregatedRatingCount: Int,
    var alternativeNames: List<Int?>,
    var playerPerspectives: List<Int?>,
    var screenshots: List<Int?>,
    var platforms: List<Int?>,
    var cover: Int,
    var themes: List<Int?>,
    var ageRatings: List<Int?>,
    var updatedAt: Int,
    var collections: List<Int?>,
    var firstReleaseDate: Int,
    var genres: List<Int?>,
    var releaseDates: List<Int?>,
    var storyline: String,
    var checksum: String,
    var totalRating: Double,
    var id: Int,
    var parentGame: Int,
    var slug: String,
    var hypes: Int,
    var franchises: List<Int?>,
    var summary: String,
    var gameModes: List<Int?>,
    var externalGames: List<Int?>,
    var url: String,
    var ratingCount: Int,
    var tags: List<Int?>,
    var languageSupports: List<Int?>,
    var artworks: List<Int?>,
    var name: String,
    var totalRatingCount: Int,
    var aggregatedRating: Double,
    var gameEngines: List<Int?>,
    var websites: List<Int?>,
    var category: Int,
    var involvedCompanies: List<Int?>,
    var isFavorite: Boolean,
) : Parcelable

//@Parcelize
//data class Games(
//    var keywords: List<Int?>?,
//    var rating: Double?,
//    var similarGames: List<Int?>?,
//    var createdAt: Int?,
//    var videos: List<Int?>?,
//    var aggregatedRatingCount: Int?,
//    var alternativeNames: List<Int?>?,
//    var playerPerspectives: List<Int?>?,
//    var screenshots: List<Int?>?,
//    var platforms: List<Int?>?,
//    var cover: Int?,
//    var themes: List<Int?>?,
//    var ageRatings: List<Int?>?,
//    var updatedAt: Int?,
//    var collections: List<Int?>?,
//    var firstReleaseDate: Int?,
//    var genres: List<Int?>?,
//    var releaseDates: List<Int?>?,
//    var storyline: String?,
//    var checksum: String?,
//    var totalRating: Double?,
//    var id: Int?,
//    var parentGame: Int?,
//    var slug: String?,
//    var hypes: Int?,
//    var franchises: List<Int?>?,
//    var summary: String?,
//    var gameModes: List<Int?>?,
//    var externalGames: List<Int?>?,
//    var url: String?,
//    var ratingCount: Int?,
//    var tags: List<Int?>?,
//    var languageSupports: List<Int?>?,
//    var artworks: List<Int?>?,
//    var name: String?,
//    var totalRatingCount: Int?,
//    var aggregatedRating: Double?,
//    var gameEngines: List<Int?>?,
//    var websites: List<Int?>?,
//    var category: Int?,
//    var involvedCompanies: List<Int?>?,
//    var isFavorite: Boolean,
//) : Parcelable